<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WayFinder.DevTools.Application\WayFinder.DevTools.Application.csproj" />
    <ProjectReference Include="..\WayFinder.DevTools.Infrastructure\WayFinder.DevTools.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
